# Generated by Django 2.2.3 on 2019-08-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='staff-default.png', upload_to='staff_photos'),
        ),
    ]
