# Generated by Django 2.2.3 on 2019-08-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='head_title',
        ),
        migrations.AddField(
            model_name='staff',
            name='english_head_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='persian_head_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
