# Generated by Django 2.2.3 on 2019-07-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20190728_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.RoleTier'),
        ),
    ]
