# Generated by Django 2.2.3 on 2019-08-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20190804_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='english_head_title',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_head',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='persian_head_title',
        ),
        migrations.AddField(
            model_name='role',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
    ]
