# Generated by Django 2.2.3 on 2019-07-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20190728_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roletier',
            name='name',
        ),
    ]
