# Generated by Django 2.2.3 on 2019-07-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_roletier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletier',
            name='english_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roletier',
            name='persian_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
