# Generated by Django 2.2.3 on 2019-08-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20190728_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
    ]
