version: '3.3'

services:
  cert:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      -nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../files/static/:/sitigo/files/static/
      - ../files/media/:/sitigo/files/media/
      - ../log/nginx/:/var/log/nginx/
      - ./config/nginx/sites-available/:/etc/nginx/sites-available/
      - ./config/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
  web:
    build: .
    container_name: web
    restart: always
    command: bash -c "export DJANGO_SETTINGS_MODULE=igo.settings.production && python3 manage.py migrate && python3 manage.py compilemessages && python3 manage.py collectstatic <<< yes && gunicorn -b 0.0.0.0:8000 --workers=4 igo.wsgi"
    volumes:
      - ../files/static/:/sitigo/files/static/
      - ../files/media/:/sitigo/files/files/media/
    depends_on:
      - db
    expose:
      - 8000
  db:
    image: postgres:latest
    container_name: db
    restart: always
    volumes:
      - ./config/db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=wowpass
