# Generated by Django 2.2.2 on 2019-07-03 06:39

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='a', max_length=400)),
                ('poster', models.ImageField(upload_to='')),
                ('persian_content', ckeditor.fields.RichTextField()),
                ('english_content', ckeditor.fields.RichTextField()),
                ('year', models.IntegerField()),
                ('files', models.ManyToManyField(to='content.FileUpload')),
            ],
        ),
    ]
