# Generated by Django 2.2.2 on 2019-07-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
