# Generated by Django 2.2.2 on 2019-07-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
