# Generated by Django 2.2.3 on 2019-07-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='content.ImageUpload'),
        ),
    ]
