# Generated by Django 2.2.2 on 2019-07-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age',
            old_name='name',
            new_name='english_name',
        ),
        migrations.AddField(
            model_name='age',
            name='persian_name',
            field=models.CharField(default='a', max_length=400),
        ),
    ]
