# Generated by Django 2.2.2 on 2019-07-02 18:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='')),
                ('content', ckeditor.fields.RichTextField()),
                ('year', models.IntegerField()),
                ('files', models.ManyToManyField(to='content.FileUpload')),
            ],
        ),
    ]
