# Generated by Django 2.2.3 on 2019-07-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190717_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
