# Generated by Django 2.2.3 on 2019-07-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20190718_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
