# Generated by Django 2.2.3 on 2019-08-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20190728_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
