# Generated by Django 2.2.3 on 2019-08-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20190804_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='english_poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
