# Generated by Django 2.2.3 on 2019-08-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_event_english_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='language',
            field=models.CharField(choices=[('fa', 'fa'), ('en', 'en')], default='fa', max_length=200),
        ),
    ]
