# Generated by Django 2.2.3 on 2019-07-17 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name_persian', models.CharField(max_length=200)),
                ('sponsor_name_english', models.CharField(max_length=200)),
                ('organizer_name_persian', models.CharField(max_length=200)),
                ('organizer_name_english', models.CharField(max_length=200)),
                ('organizer_image', models.ImageField(upload_to='organizer')),
                ('sponsor_image', models.ImageField(upload_to='sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_page_slideshow')),
                ('persian_caption', models.CharField(default='a', max_length=300)),
                ('english_caption', models.CharField(default='a', max_length=300)),
                ('homePage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_image', to='intro.HomePage')),
            ],
        ),
    ]
