# Generated by Django 2.2.3 on 2019-07-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageimage',
            name='english_caption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='persian_caption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
