# Generated by Django 2.2.3 on 2019-07-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageimage',
            old_name='caption',
            new_name='english_caption',
        ),
        migrations.AddField(
            model_name='homepageimage',
            name='persian_caption',
            field=models.CharField(default='a', max_length=300),
        ),
    ]
