# Generated by Django 2.2.2 on 2019-07-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagedata',
            name='name',
            field=models.CharField(default='asghar', max_length=10),
        ),
    ]
