# Generated by Django 2.2.2 on 2019-07-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_homepagedata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='home_page_data',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='home_page_data',
        ),
        migrations.DeleteModel(
            name='HomePageData',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
