# Generated by Django 2.2.2 on 2019-07-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='headline',
            field=models.TextField(default='headline', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogdir',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
