# Generated by Django 2.2.3 on 2019-07-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190706_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
