# Generated by Django 2.2.3 on 2019-07-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
        migrations.AddField(
            model_name='country',
            name='english_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='persian_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='english_caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='persian_caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
