# Generated by Django 2.2.3 on 2019-07-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190727_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='english_caption',
            field=models.CharField(blank=True, default='default', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='persian_caption',
            field=models.CharField(blank=True, default='default', max_length=100, null=True),
        ),
    ]
