# Generated by Django 2.2.3 on 2019-08-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.City'),
        ),
    ]
