# Generated by Django 2.2.3 on 2019-08-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_image_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='english_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='city',
            name='persian_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='english_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='persian_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='english_caption',
            field=models.CharField(blank=True, default='default', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='persian_caption',
            field=models.CharField(blank=True, default='default', max_length=200, null=True),
        ),
    ]
