# Generated by Django 2.2.3 on 2019-08-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20190801_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.City'),
        ),
    ]
