# Generated by Django 2.2.3 on 2019-07-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fa', 'persian'), ('en', 'english')], default='fa', max_length=128)),
                ('question', models.CharField(max_length=400)),
                ('answer', models.CharField(max_length=400)),
            ],
        ),
    ]
