# Generated by Django 2.2.3 on 2019-07-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='FAQ',
        ),
    ]
