# Generated by Django 2.2.3 on 2019-07-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='scoreboard')),
                ('contest_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.ContestTier')),
            ],
        ),
    ]
